apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-internal
  namespace: tech.prod
spec:
  podSelector:
    matchLabels:
      app: app_python
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector: {}
